"""
Django settings for attendance_system project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import pymysql
from dotenv import load_dotenv
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Load environment variables
load_dotenv()

# Configure PyMySQL
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# ENVIRONMENT CONFIGURATION
# =============================================================================
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')
IS_PRODUCTION = ENVIRONMENT == 'production'
IS_DEVELOPMENT = ENVIRONMENT == 'development'
IS_TESTING = ENVIRONMENT == 'testing'

# =============================================================================
# SECURITY SETTINGS
# =============================================================================
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-eg&hkh!w@e(%wx6aztj4+flb*fcl&a)*2zeh8rzzf^#n31!vb^')
DEBUG = not IS_PRODUCTION

# Allowed hosts configuration
if IS_PRODUCTION:
    ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,company.d0s369.co.in').split(',') if host.strip()]
else:
    ALLOWED_HOSTS = ['*']

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'https://company.d0s369.co.in',
    'http://localhost:5173',
    'http://127.0.0.1:5174',
    'https://dosmanagers.dishaonlinesolution.in',
    'https://dosemployees.dishaonlinesolution.in',
    'https://admindos.dishaonlinesolution.in',
    'https://dosaccounts.dishaonlinesolution.in'
]

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================

# Django Core Apps
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
    
# Third Party Apps
THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',  # Django Channels for WebSocket support
]

# Admin Theme Apps (must be loaded before django.contrib.admin)
ADMIN_THEME_APPS = [
    'unfold',  # django-unfold admin theme
    'unfold.contrib.filters',  # optional, if special filters are needed
    'unfold.contrib.forms',  # optional, if special form elements are needed
    'unfold.contrib.import_export',  # optional, if django-import-export package is used
]
    
# Local Apps
LOCAL_APPS = [
    'core.apps.CoreConfig',
    'coreapp.apps.CoreappConfig',
]

# Combine all apps
INSTALLED_APPS = ADMIN_THEME_APPS + DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# =============================================================================
# MIDDLEWARE CONFIGURATION
# =============================================================================

# Core Django Middleware
DJANGO_MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Third Party Middleware
THIRD_PARTY_MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
]

# Custom Middleware
CUSTOM_MIDDLEWARE = [
    'core.middleware.AdminCSPMiddleware',  # Allow unsafe-eval for admin panel (django-unfold/Alpine.js)
    'core.middleware.APIAuthenticationDebugMiddleware',  # Debug API authentication
    'core.middleware.DatabaseConnectionMiddleware',  # Database connection management
]

# Combine all middleware
MIDDLEWARE = THIRD_PARTY_MIDDLEWARE + DJANGO_MIDDLEWARE + CUSTOM_MIDDLEWARE

ROOT_URLCONF = 'attendance_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'attendance_system.wsgi.application'

# ASGI Application for WebSocket support
ASGI_APPLICATION = 'attendance_system.asgi.application'

# Channels Configuration
if IS_PRODUCTION:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [(os.environ.get('REDIS_HOST', 'localhost'), int(os.environ.get('REDIS_PORT', 6379)))],
                "capacity": 1500,
                "expiry": 10,
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }


# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================

# Database connection settings
DB_ENGINE = os.environ.get('DB_ENGINE', 'django.db.backends.mysql')
DB_NAME = os.environ.get('DB_NAME', 'u434975676_DOS')
DB_USER = os.environ.get('DB_USER', 'u434975676_bimal')
DB_PASSWORD = os.environ.get('DB_PASSWORD', 'DishaSolution@8989')
DB_HOST = os.environ.get('DB_HOST', '193.203.184.215')
DB_PORT = os.environ.get('DB_PORT', '3306')

# Database options for MySQL
DB_OPTIONS = {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', time_zone='+05:30', wait_timeout=28800, interactive_timeout=28800",
            'connect_timeout': 60,
            'read_timeout': 60,
            'write_timeout': 60,
            'autocommit': True,
            'max_allowed_packet': 16777216,  # 16MB
            'sql_mode': 'STRICT_TRANS_TABLES',
            'use_unicode': True,
            'isolation_level': None,
}

# Database configuration
DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'OPTIONS': DB_OPTIONS,
        'CONN_MAX_AGE': 600 if IS_PRODUCTION else 300,
        'ATOMIC_REQUESTS': False,
        'AUTOCOMMIT': True,
    }
}

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =============================================================================
# INTERNATIONALIZATION
# =============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True


# =============================================================================
# STATIC AND MEDIA FILES
# =============================================================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Static files storage for production
if IS_PRODUCTION:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

MEDIA_URL =os.environ.get('MEDIA_URL','/media/')
MEDIA_ROOT =os.environ.get('MEDIA_ROOT',BASE_DIR / 'media')

# =============================================================================
# AUTHENTICATION AND USER MODEL
# =============================================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.CustomUser'

# Custom Authentication Backend
AUTHENTICATION_BACKENDS = [
    'core.authentication_backend.CustomAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# =============================================================================
# REST FRAMEWORK CONFIGURATION
# =============================================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'EXCEPTION_HANDLER': 'core.exception_handlers.custom_exception_handler',
}

# =============================================================================
# JWT CONFIGURATION
# =============================================================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
}


# =============================================================================
# CORS CONFIGURATION
# =============================================================================
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    'https://dosemployees.dishaonlinesolution.in',
    'https://dosmanagers.dishaonlinesolution.in',
    'https://admindos.dishaonlinesolution.in',
    'https://dosaccounts.dishaonlinesolution.in',
    'http://localhost:5173',
    'http://127.0.0.1:5174',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.dishaonlinesolution\.in$",
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'HEAD',
]
CORS_EXPOSE_HEADERS = [
    'Content-Type', 
    'X-CSRFToken',
    'Authorization',
    'Access-Control-Allow-Origin',
    'Access-Control-Allow-Methods',
    'Access-Control-Allow-Headers',
]
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours
CORS_URLS_REGEX = r'^.*$'  # Allow CORS for all URLs
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'access-control-allow-origin',
    'access-control-allow-methods',
    'access-control-allow-headers',
    'cache-control',
    'pragma',
    'expires',
    'x-csrftoken',
    'x-requested-with',
    'authorization',
    'content-type',
    'accept',
    'origin',
    'user-agent',
]
CORS_ALLOW_PRIVATE_NETWORK = True
CORS_ALLOW_PRIVATE_NETWORK_ACCESS = True

# Additional CORS settings for better compatibility
CORS_ALLOW_ALL_HEADERS = True

# =============================================================================
# SECURITY SETTINGS
# =============================================================================
# X_FRAME_OPTIONS for django-unfold (needs SAMEORIGIN for modals)
X_FRAME_OPTIONS = 'SAMEORIGIN'
SILENCED_SYSTEM_CHECKS = ['security.W019']  # Silence warning about X_FRAME_OPTIONS

# Content Security Policy - Allow inline scripts for django-unfold
# This ensures filter panel JavaScript works correctly
if IS_PRODUCTION:
    # In production, you may need to configure CSP headers in your web server (nginx/apache)
    # For now, we'll rely on the web server configuration
    pass

if IS_PRODUCTION:
    # Security middleware settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # X_FRAME_OPTIONS is set above for django-unfold compatibility
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# =============================================================================
# DJANGO-UNFOLD CONFIGURATION
# =============================================================================
def environment_callback(request):
    """Return environment name for django-unfold"""
    return ENVIRONMENT

UNFOLD = {
    "SITE_TITLE": "Disha Online Solution",
    "SITE_HEADER": "Disha Online Solution",
    "SITE_URL": "/",
    "SITE_ICON": None,
    "SITE_LOGO": None,
    "SITE_SYMBOL": "settings",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": environment_callback,
    "DASHBOARD_CALLBACK": None,
    "LOGIN": {
        "image": None,
        "redirect_after": None,
    },
    "STYLES": [
        # Add custom CSS files here if needed
        # lambda request: static("css/custom-admin.css"),
    ],
    "SCRIPTS": [
        # Add custom JS files here if needed
        # lambda request: static("js/custom-admin.js"),
    ],
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
        },
    },
}

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
            'detailed': {
                'format': '{levelname} {asctime} {name} {process:d} {thread:d} {pathname}:{lineno:d} {funcName} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
            'level': 'INFO' if IS_PRODUCTION else 'DEBUG',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR / 'logs' / 'django.log',
                'maxBytes': 10485760,  # 10MB
            'backupCount': 5 if IS_PRODUCTION else 3,
                'formatter': 'verbose',
            },
            'error_file': {
                'level': 'ERROR',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR / 'logs' / 'error.log',
                'maxBytes': 10485760,  # 10MB
            'backupCount': 5 if IS_PRODUCTION else 3,
                'formatter': 'detailed',
            },
            'console': {
            'level': 'WARNING' if IS_PRODUCTION else 'DEBUG',
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
            'database': {
            'level': 'ERROR' if IS_PRODUCTION else 'DEBUG',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR / 'logs' / 'database.log',
                'maxBytes': 10485760,  # 10MB
            'backupCount': 5 if IS_PRODUCTION else 3,
                'formatter': 'detailed',
            },
        },
        'root': {
            'handlers': ['console', 'file', 'error_file'],
        'level': 'INFO' if IS_PRODUCTION else 'DEBUG',
        },
        'loggers': {
            'django': {
                'handlers': ['console', 'file'],
            'level': 'INFO' if IS_PRODUCTION else 'DEBUG',
                'propagate': False,
            },
            'django.db': {
                'handlers': ['database'],
            'level': 'ERROR' if IS_PRODUCTION else 'DEBUG',
                'propagate': False,
            },
            'django.security': {
                'handlers': ['console', 'file', 'error_file'],
                'level': 'WARNING',
                'propagate': False,
            },
            'django.request': {
                'handlers': ['console', 'file', 'error_file'],
                'level': 'ERROR',
                'propagate': False,
            },
            'core': {
                'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO' if IS_PRODUCTION else 'DEBUG',
                'propagate': False,
            },
        },
    }

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND','django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST','smtp.gmail.com')
EMAIL_PORT = os.environ.get('EMAIL_PORT',587)
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS',True)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER','info.dishaonlinesoution@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD','ktrc uzzy upkr ftbv')
DEFAULT_FROM_EMAIL =os.environ.get('DEFAULT_FROM_EMAIL','Disha Online Solution <info.dishaonlinesoution@gmail.com>')
SERVER_EMAIL =os.environ.get('SERVER_EMAIL','info.dishaonlinesoution@gmail.com')

# =============================================================================
# CELERY CONFIGURATION
# =============================================================================
CELERY_BROKER_URL =os.environ.get('CELERY_BROKER_URL','redis://localhost:6379/0')
CELERY_RESULT_BACKEND =os.environ.get('CELERY_RESULT_BACKEND','redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE =os.environ.get('CELERY_TIMEZONE',TIME_ZONE)

# =============================================================================
# SESSION AND CACHE CONFIGURATION
# =============================================================================
SESSION_ENGINE =os.environ.get('SESSION_ENGINE','django.contrib.sessions.backends.db')
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

CACHES = {
    'default': {
        'BACKEND':os.environ.get('CACHES_BACKEND','django.core.cache.backends.locmem.LocMemCache'),
        'LOCATION': 'unique-snowflake',
        'TIMEOUT':os.environ.get('CACHES_TIMEOUT',300),
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# =============================================================================
# FILE UPLOAD SETTINGS
# =============================================================================
FILE_UPLOAD_MAX_MEMORY_SIZE =os.environ.get('FILE_UPLOAD_MAX_MEMORY_SIZE',10485760)  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE =os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE',10485760)  # 10MB
FILE_UPLOAD_PERMISSIONS =os.environ.get('FILE_UPLOAD_PERMISSIONS',0o644)

# =============================================================================
# ADDITIONAL SECURITY SETTINGS
# =============================================================================
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# =============================================================================
# APPLICATION-SPECIFIC SETTINGS
# =============================================================================

# Attendance Service Configuration
AUTO_START_ATTENDANCE_SERVICE = os.environ.get('AUTO_START_ATTENDANCE_SERVICE', 'false').lower() == 'true'

# Company Information for PDF Documents
COMPANY_NAME = os.environ.get('COMPANY_NAME', 'Disha Online Solution')
COMPANY_ADDRESS = os.environ.get('COMPANY_ADDRESS', 'Office Address, City, State, ZIP')
COMPANY_PHONE = os.environ.get('COMPANY_PHONE', '+91 (XXX) XXX-XXXX')
COMPANY_EMAIL = os.environ.get('COMPANY_EMAIL', 'info.dishaonlinesoution@gmail.com')
COMPANY_WEBSITE = os.environ.get('COMPANY_WEBSITE', 'www.dishaonlinesolution.com')
SITE_URL = os.environ.get('SITE_URL', 'https://company.d0s369.co.in')