# Generated by Django 5.2.4 on 2025-08-25 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biometric_id',
            field=models.CharField(blank=True, help_text='Biometric ID from ESSL device', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, help_text='Device ID from ESSL device', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='device_status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='last_attendance_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sync_interval',
            field=models.IntegerField(default=5, help_text='Sync interval in minutes'),
        ),
        migrations.CreateModel(
            name='ESSLAttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('biometric_id', models.CharField(max_length=50)),
                ('punch_time', models.DateTimeField()),
                ('punch_type', models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out')], max_length=10)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-punch_time'],
                'indexes': [models.Index(fields=['biometric_id', 'punch_time'], name='core_esslat_biometr_f0fe25_idx'), models.Index(fields=['device', 'punch_time'], name='core_esslat_device__b84992_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkingHoursSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard_hours', models.DecimalField(decimal_places=2, default=9.0, help_text='Standard working hours per day', max_digits=4)),
                ('start_time', models.TimeField(default='09:00:00', help_text='Standard start time')),
                ('end_time', models.TimeField(default='18:00:00', help_text='Standard end time')),
                ('late_threshold', models.IntegerField(default=15, help_text='Minutes after start time to consider late')),
                ('half_day_threshold', models.IntegerField(default=240, help_text='Minutes to consider half day (4 hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.office')),
            ],
            options={
                'verbose_name_plural': 'Working Hours Settings',
                'unique_together': {('office',)},
            },
        ),
    ]
