# Generated by Django 5.2.4 on 2025-09-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enhance_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='id_card_data',
            field=models.JSONField(blank=True, help_text='Data specific to ID cards', null=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter'), ('salary_increment', 'Salary Increment Letter'), ('salary_slip', 'Salary Slip'), ('id_card', 'Employee ID Card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='document_type',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter'), ('salary_increment', 'Salary Increment Letter'), ('salary_slip', 'Salary Slip'), ('id_card', 'Employee ID Card')], max_length=50),
        ),
    ]
