# Generated by Django 5.2.4 on 2025-08-25 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_office', to=settings.AUTH_USER_MODEL),
        ),
    ]
