# Generated by Django 5.2.5 on 2025-08-27 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_office_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_user_id', models.CharField(help_text='User ID from the device', max_length=50)),
                ('device_user_name', models.CharField(help_text='Name from the device', max_length=100)),
                ('device_user_privilege', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='user', max_length=20)),
                ('device_user_password', models.CharField(blank=True, help_text='Password from device (if available)', max_length=50)),
                ('device_user_group', models.CharField(blank=True, help_text='Group from device', max_length=50)),
                ('device_user_card', models.CharField(blank=True, help_text='Card number from device', max_length=50)),
                ('is_mapped', models.BooleanField(default=False, help_text='Whether this device user is mapped to a system user')),
                ('mapping_notes', models.TextField(blank=True, help_text='Notes about the mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_users', to='core.device')),
                ('system_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['device', 'device_user_id'],
                'unique_together': {('device', 'device_user_id')},
            },
        ),
    ]
