# Generated by Django 5.2.4 on 2025-09-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_salary_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarytemplate',
            options={'ordering': ['designation_name', 'office_name'], 'verbose_name': 'Salary Template', 'verbose_name_plural': 'Salary Templates'},
        ),
        migrations.RenameIndex(
            model_name='salary',
            new_name='core_salary_employe_b83223_idx',
            old_name='core_salary_employee_idx',
        ),
        migrations.RenameIndex(
            model_name='salary',
            new_name='core_salary_status_0a0b30_idx',
            old_name='core_salary_status_idx',
        ),
        migrations.RenameIndex(
            model_name='salary',
            new_name='core_salary_approve_46d720_idx',
            old_name='core_salary_approved_idx',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='id_card_data',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='house_rent_allowance',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='income_tax',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='medical_allowance',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='other_allowances',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='professional_tax',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='provident_fund',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='transport_allowance',
        ),
        migrations.AlterUniqueTogether(
            name='salarytemplate',
            unique_together={('designation_name', 'office_name')},
        ),
        migrations.AddField(
            model_name='salarytemplate',
            name='designation_name',
            field=models.CharField(default='Default Designation', help_text='Designation name', max_length=200),
        ),
        migrations.AddField(
            model_name='salarytemplate',
            name='office_name',
            field=models.CharField(default='Default Office', help_text='Office name', max_length=200),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter'), ('salary_increment', 'Salary Increment Letter'), ('salary_slip', 'Salary Slip')], max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='document_type',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter'), ('salary_increment', 'Salary Increment Letter'), ('salary_slip', 'Salary Slip')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Personal Leave'), ('sick', 'Sick Leave'), ('annual', 'Annual Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('other', 'Other')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='house_rent_allowance',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='medical_allowance',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='office',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='other_allowances',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='professional_tax',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='provident_fund_percentage',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='transport_allowance',
        ),
    ]
