# Generated by Django 5.2.5 on 2025-08-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_deviceuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='office',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='office',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='office',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='office',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
