# Generated by Django 5.2.4 on 2025-09-28 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recreate_salary_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-salary_month', '-created_at'], 'verbose_name': 'Salary', 'verbose_name_plural': 'Salaries'},
        ),
        migrations.RemoveConstraint(
            model_name='salarytemplate',
            name='unique_designation_office_name',
        ),
        migrations.AddField(
            model_name='salary',
            name='per_day_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per day pay amount (used for calculation)', max_digits=10),
        ),
        migrations.AddField(
            model_name='salarytemplate',
            name='per_day_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per day pay amount (used for calculation)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, help_text='Basic salary amount (for reference only)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salary',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='salary',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarytemplate',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, help_text='Basic salary amount (for reference only)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salarytemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('employee', 'salary_month')},
        ),
        migrations.AlterUniqueTogether(
            name='salarytemplate',
            unique_together={('designation_name', 'office_name')},
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['employee', 'salary_month'], name='core_salary_employe_b83223_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['status', 'salary_month'], name='core_salary_status_0a0b30_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['approved_by', 'approved_at'], name='core_salary_approve_46d720_idx'),
        ),
    ]
