# Generated by Django 5.2.5 on 2025-08-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_office_city_office_country_office_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('salary_slip', 'Salary Slip'), ('offer_letter', 'Offer Letter'), ('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('aadhar_card', 'Aadhar Card'), ('pan_card', 'PAN Card'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License'), ('passport', 'Passport'), ('birth_certificate', 'Birth Certificate'), ('educational_certificate', 'Educational Certificate'), ('experience_certificate', 'Experience Certificate'), ('medical_certificate', 'Medical Certificate'), ('bank_statement', 'Bank Statement'), ('other', 'Other')], max_length=30),
        ),
    ]
