# Generated by Django 5.2.4 on 2025-09-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_per_day_pay_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gross salary (per_day_pay * worked_days)', max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net salary after deductions', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('upi', 'Upi'), ('other', 'Other')], default='bank_transfer', max_length=20),
        ),
    ]
