# Generated by Django 5.2.4 on 2025-09-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_attendance_unique_constraint'),
        ('core', '0007_add_document_types'),
    ]

    operations = [
    ]
