# Generated by Django 5.2.4 on 2025-09-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_attendance_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghourssettings',
            name='end_time',
            field=models.TimeField(default='19:00:00', help_text='Standard end time'),
        ),
        migrations.AlterField(
            model_name='workinghourssettings',
            name='late_coming_threshold',
            field=models.TimeField(default='11:30:00', help_text='Time after which check-in is considered late coming'),
        ),
        migrations.AlterField(
            model_name='workinghourssettings',
            name='start_time',
            field=models.TimeField(default='10:00:00', help_text='Standard start time'),
        ),
    ]
