# Generated by Django 5.2.4 on 2025-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_employee_role_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='paid', max_length=20),
        ),
    ]
