# Generated by Django 5.2.4 on 2025-09-05 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('salary_increment', 'Salary Increment Letter'), ('salary_slip', 'Salary Slip')], max_length=50)),
                ('template_content', models.TextField(help_text='HTML template with Django template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Document Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('salary_increment', 'Salary Increment Letter'), ('salary_slip', 'Salary Slip')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Generated HTML content')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_documents/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('offer_data', models.JSONField(blank=True, help_text='Data specific to offer letters', null=True)),
                ('increment_data', models.JSONField(blank=True, help_text='Data specific to salary increment letters', null=True)),
                ('salary_data', models.JSONField(blank=True, help_text='Data specific to salary slips', null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents_by', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documenttemplate')),
            ],
            options={
                'verbose_name_plural': 'Generated Documents',
                'ordering': ['-generated_at'],
            },
        ),
    ]
