# Generated by Django 5.2.4 on 2025-10-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_salary_status_and_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day_status',
            field=models.CharField(choices=[('complete_day', 'Complete Day'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('upcoming', 'Upcoming')], default='complete_day', max_length=15),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('upcoming', 'Upcoming')], default='present', max_length=10),
        ),
    ]
