# Generated by Django 5.2.4 on 2025-09-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_resignation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignation',
            name='last_working_date',
            field=models.DateField(blank=True, help_text='Automatically calculated last working date (resignation_date + notice_period)', null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='notice_period_days',
            field=models.IntegerField(default=30, help_text='Notice period in days (15 or 30)'),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='resignation_date',
            field=models.DateField(help_text='Resignation submission date'),
        ),
    ]
