# Generated by Django 5.2.4 on 2025-10-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shift_employeeshiftassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='salary',
            name='status_reason',
            field=models.TextField(blank=True, help_text='Reason for current status if applicable'),
        ),
    ]
