# Generated by Django 5.2.4 on 2025-09-08 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_update_resignation_last_working_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='manager',
        ),
        migrations.AddField(
            model_name='office',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Up to 5 managers can be assigned to an office', limit_choices_to={'role': 'manager'}, related_name='managed_offices', to=settings.AUTH_USER_MODEL),
        ),
    ]
