# Generated by Django 5.2.4 on 2025-10-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_salary_rejection_reason_salary_status_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='upi_qr',
            field=models.FileField(blank=True, help_text='User uploaded UPI QR code (image/pdf/any)', null=True, upload_to='user_qr_codes/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='upi_qr_reason',
            field=models.TextField(blank=True, help_text='Reason or description for UPI QR (optional)'),
        ),
    ]
