# Generated by Django 5.2.4 on 2025-09-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_department_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_card',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar card number', max_length=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_card',
            field=models.CharField(blank=True, help_text='10-character PAN card number', max_length=10),
        ),
    ]
