# Generated by Django 5.2.4 on 2025-10-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customuser_upi_qr_customuser_upi_qr_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='upi_qr_reason',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='upi_qr',
            field=models.ImageField(blank=True, help_text='User uploaded UPI QR image (PNG/JPG/WebP)', null=True, upload_to='user_qr_codes/'),
        ),
    ]
