# Generated by Django 5.2.4 on 2025-09-15 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_aadhaar_pan_fields'),
    ]

    operations = [
        # Add foreign key constraint to existing department_id column
        migrations.RunSQL(
            "ALTER TABLE core_customuser ADD CONSTRAINT fk_customuser_department FOREIGN KEY (department_id) REFERENCES core_department(id);",
            reverse_sql="ALTER TABLE core_customuser DROP FOREIGN KEY fk_customuser_department;"
        ),
    ]
