# Generated by Django 5.2.4 on 2025-09-15 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20250915_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.ForeignKey(blank=True, db_column='designation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.designation'),
        ),
    ]
