# Generated by Django 5.2.4 on 2025-09-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20250915_1207'),
    ]

    operations = [
        # Step 1: Make designation column nullable
        migrations.RunSQL(
            "ALTER TABLE core_customuser MODIFY COLUMN designation VARCHAR(100) NULL;",
            reverse_sql="ALTER TABLE core_customuser MODIFY COLUMN designation VARCHAR(100) NOT NULL;"
        ),
        
        # Step 2: Clear existing designation data
        migrations.RunSQL(
            "UPDATE core_customuser SET designation = NULL;",
            reverse_sql="UPDATE core_customuser SET designation = 'Employee';"
        ),
        
        # Step 3: Rename the existing designation column
        migrations.RunSQL(
            "ALTER TABLE core_customuser CHANGE COLUMN designation designation_temp VARCHAR(100) NULL;",
            reverse_sql="ALTER TABLE core_customuser CHANGE COLUMN designation_temp designation VARCHAR(100) NULL;"
        ),
        
        # Step 4: Add new designation_id column for ForeignKey
        migrations.RunSQL(
            "ALTER TABLE core_customuser ADD COLUMN designation_id CHAR(32) NULL;",
            reverse_sql="ALTER TABLE core_customuser DROP COLUMN designation_id;"
        ),
        
        # Step 5: Update the model field
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.designation'),
        ),
        
        # Step 6: Drop the temporary column
        migrations.RunSQL(
            "ALTER TABLE core_customuser DROP COLUMN designation_temp;",
            reverse_sql="ALTER TABLE core_customuser ADD COLUMN designation_temp VARCHAR(100) NULL;"
        ),
    ]
